export const IPC_CHANNELS = {
  listDecks: 'decks:list',
  createDeck: 'decks:create',
  listCards: 'cards:list',
  createCard: 'cards:create',
  updateCard: 'cards:update',
  getDueCard: 'review:next',
  reviewCard: 'review:rate',
  snoozeCard: 'review:snooze',
  getStats: 'stats:get',
  startReviewSession: 'session:start',
  endReviewSession: 'session:end',
  getNextReviewInfo: 'review:next-info',
  getDueCardWithPriority: 'review:next-with-poor',
  moveDeck: 'decks:move',
  deleteDeck: 'decks:delete',
  getDeletePreview: 'decks:delete-preview',
} as const;
