import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'path';

import { CardCrafterDB } from './main/db';
import { IPC_CHANNELS } from './shared/ipc';
import type { CreateCardInput, CreateDeckInput, ReviewInput } from './shared/types';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let db: CardCrafterDB | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    minHeight: 640,
    minWidth: 980,
    backgroundColor: '#f5f7fb',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  if (process.env.NODE_ENV === 'development') {
    //mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  const dbPath = path.join(app.getPath('userData'), 'cardcrafter.db');
  db = new CardCrafterDB(dbPath);
  registerIpcHandlers(db);
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

function registerIpcHandlers(database: CardCrafterDB) {
  ipcMain.handle(IPC_CHANNELS.listDecks, () => database.listDecks());
  ipcMain.handle(IPC_CHANNELS.createDeck, (_event, input: CreateDeckInput) =>
    database.createDeck(input),
  );
  ipcMain.handle(IPC_CHANNELS.listCards, (_event, deckId: string) =>
    database.listCards(deckId),
  );
  ipcMain.handle(IPC_CHANNELS.createCard, (_event, input: CreateCardInput) =>
    database.createCard(input),
  );
  ipcMain.handle(IPC_CHANNELS.getDueCard, (_event, deckId?: string | null) =>
    database.getDueCard(deckId ?? null),
  );
  ipcMain.handle(IPC_CHANNELS.reviewCard, (_event, input: ReviewInput) =>
    database.reviewCard(input.cardId, input.q, input.durationMs ?? null),
  );
  ipcMain.handle(
    IPC_CHANNELS.snoozeCard,
    (_event, cardId: string, minutes?: number) =>
      database.snoozeCard(cardId, minutes ?? 10),
  );
  ipcMain.handle(IPC_CHANNELS.getStats, (_event, deckId?: string | null) =>
    database.getStats(deckId ?? null),
  );
}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
